#! /bin/sh
### BEGIN INIT INFO
# Provides:          robot
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run the robot python if it exist
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/opt/robot/src/imaging:/opt/robot/src/platform:/opt/robot/src/weedkiller:/opt/robot/src/test
ROBOHOME=/opt/robot
export PATH PYTHONPATH ROBOHOME


. /lib/init/vars.sh
. /lib/lsb/init-functions


case "$1" in
    start)
	python /opt/robot/src/platform/daemon.py &
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop|status)
        # No-op
        exit 0
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
